# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93c355117cdcda5db2876d48af939ef18a1d9ae36548fcebdb1aa785e4274105051994b51c3e601ed702f98ca9ef26dda3bb2c31e191649873eac1562cd60b5a

test:
  secret_key_base: acf0ba077b624acd751d763bd77f49779b98ccb61564599c0729f2168b570b42cfb0d7d17eb3cb6c73b17ed46f5ff130b17b083a7211630fec9b4f5687269b7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
